#!/usr/bin/env bash
# Install nginx on server and start it

sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R $USER:$USER /var/www
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
